# Generated by Django 4.0.5 on 2023-01-31 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_classname_slug'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='classname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.classname'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.specialization'),
        ),
    ]
