# Generated by Django 4.0.5 on 2023-02-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_scores_classname_alter_scores_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
