# Generated by Django 4.0.5 on 2023-01-17 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField()),
                ('address', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('phone', models.CharField(max_length=11)),
                ('specialization', models.CharField(max_length=255)),
                ('joining_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classname')),
            ],
        ),
        migrations.AddField(
            model_name='classname',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.specialization'),
        ),
    ]
