# Generated by Django 4.0.5 on 2023-01-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('infouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.infouser')),
            ],
        ),
    ]
