# Generated by Django 4.0.5 on 2023-01-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_status'),
        ('subjects', '0002_subject_teaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.specialization'),
        ),
    ]
