# Generated by Django 4.0.5 on 2023-03-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
    ]
