# Generated by Django 4.0.5 on 2023-04-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_infouser_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='student',
        ),
    ]
