# Generated by Django 4.0.5 on 2023-04-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_infouser_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='isStudent',
        ),
    ]
